### ISSUE TITLE
Performance compared to ordinary Julia arrays

### ISSUE THREAD

**Issue by dfdx** [JuliaGPU/OpenCL.jl#102]
Let's take just a little bit modified example from README:

```
const sum_kernel = "
   __kernel void sum(__global const float *a,
                     __global float *b)
{
      int gid = get_global_id(0);
      b[gid] = a[gid] + b[gid];
}
"
a = rand(Float32, 50_000)
b = rand(Float32, 50_000)

device, ctx, queue = cl.create_compute_context()

a_buff = cl.Buffer(Float32, ctx, (:r, :copy), hostbuf=a)
b_buff = cl.Buffer(Float32, ctx, (:rw, :copy), hostbuf=b)    

p = cl.Program(ctx, source=sum_kernel) |> cl.build!
k = cl.Kernel(p, "sum")
cl.set_args!(k, a_buff, b_buff)
```

Running this example on my machine like this: 

```
ev = cl.enqueue_kernel(queue, k, size(a))  # to create ev in global scope
@time begin
    for i=1:10_000
        ev = cl.enqueue_kernel(queue, k, size(a))
    end
    cl.wait(ev)
end
```

takes 0.328125 seconds (and 5Mb). At the same time doing the same thing for native Julia arrays: 

```
@time for i=1:10_000
     sum!(a, b)
end
```

it takes 0.251480 seconds (and 780Kb).

Summing arrays of numbers looks like a perfect use case for GPU computing. Yet, it's worse than ordinary addition performed on CPU. 

Are these results specific to my setup only or this is something expectable? 

---

Device: GeForce GT 630M on NVIDIA CUDA
Driver: nvidia-352.63

**Comment by jakebolewski** [comment]
Welcome to the wonderful world of Ahmdel's law and GPU computing.

Summing numbers is decidedly *not* a great example for GPU computing.  You incur a serial overhead every time you communicate with the GPU and your example does that every iteration.

**Comment by dfdx** [comment]
Basically, I expected the size of the problem (50k of floats) to be enough to overcome communication overhead, but I've got 2x speedup only on 100M of elements, which sounds pretty huge for me. Is there anything I can do to improve performance in the test? Something instead of `sum()`?

**Comment by dfdx** [comment]
Seems like one of the causes is performance of my GPU itself - I tried very similar test on a different one with a newer NVidia card and it gave 2.5 boost compared to CPU.

**Comment by jakebolewski** [comment]
You can do multiple things:

Try to increase arithmetic intensity of the kernel by fusing them.
You can lazy enqueue kernels on the gpu by declaring task dependencies, right now you are waiting for the kernel to complete every iteration. 

Since the arithmetic intensity is so low, what you are really measuring in memory bandwidth on the GPU with the above example (+ the communication costs between the GPU <-> CPU with the `wait` barrier).  More expensive cards usually have higher overall memory bandwidths.  GPU memory bandwidth is much greater than CPU memory bandwidth, at the cost of higher latency (you can get a lot of data quickly, but the latency for a given memory fetch is high).

**Comment by dfdx** [comment]
> You can lazy enqueue kernels on the gpu by declaring task dependencies, right now you are waiting for the kernel to complete every iteration. 

I missed this point and thought `enqueue_kernel()` returns immediately (hence this additional logic with return event). Can you please provide an example how to lazily enqueue a kernel?

**Comment by vchuravy** [comment]
`enqueue_kernel` takes a kwarg `wait_on` that can be a vector of events or nothing. So you can schedule all your operations on the device and the wait for the last one to finish.

**Comment by dfdx** [comment]
@vchuravy Do you mean something like this: 

````
@time begin               
    for i=1:10
        wait_on = events[1:i-1]            
        events[i] = cl.enqueue_kernel(queue, k, size(a), 256, wait_on=wait_on)
    end
    cl.wait(events[10])
end
```

If so, this behaves the same as code above. Note, that in my first snippet `cl.wait()` is outside the loop, i.e. I wait only for the last event.

**Comment by vchuravy** [comment]
@dfdx 
I was thinking of

```julia
@time begin
wait_on = nothing               
    for i=1:10
        wait_on = cl.enqueue_kernel(queue, k, size(a), 256, wait_on=wait_on)
    end
    cl.wait(wait_on)
end
```

You should see a performance difference for big problem sizes, because you allow OpenCL to start copying data earlier.

**Comment by dfdx** [comment]
I modified it a little bit to make it runnable, and result is exactly the same as in my version: 

Modified version (takes 0.490161 seconds)
```
@time begin
        wait_on = cl.Event[]
        for i=1:10
            wait_on = cl.enqueue_kernel(queue, k, size(a), 256,
                                        wait_on=[wait_on])
        end
        cl.wait(wait_on)
    end
```
My original version (takes 0.486604 seconds)
```
ev = cl.enqueue_kernel(queue, k, size(a))
@time begin
    for i=1:10
        ev = cl.enqueue_kernel(queue, k, size(a))
    end
    cl.wait(ev)
end
```

I believe in all cases the same thing happens: all kernels are quickly enqueued and then executed one by one. In your version waiting on the last event works because all kernels are provided with `wait_on` option with previous event. In my version there's no wait-on list, but kernels still run sequentially because of strict in order execution. 

For both tests I used `a` and `b` of size 100 000 000 elements (~381 Mb), so increasing it even 10 times will explode my GPU memory. Anyway, it sounds like a reasonably big problem size. 

Note, though, that these are results for my somewhat old GPU. Would be nice if somebody could check it on a newer device and post results.

**Comment by vchuravy** [comment]
I can try early next week on a GPU cluster I have access to.

**Comment by dfdx** [comment]
Great, thank you.

**Comment by jpsamaroo** [comment]
I just tested this on a Macbook Pro 2015 with an i7-4770HQ 2.2GHz CPU, and what I believe is an Iris Pro 6200 GPU. Running the second test listed (the first threw an error at me) with 100,000,000 elements on the GPU takes 1.0 seconds, and on the CPU, it takes 3.7 seconds.

For a more complex kernel and on a decent GPU (the Iris Pro isn't really that fast as far as modern GPUs go), I would imagine that this could be many, many times faster. In fact, I know it is, because I'm currently using this package for running the Izhikevich spiking neuron model (http://www.izhikevich.org/publications/spikes.pdf) for my personal research, and it can chew through 1,000 iterations of 1,048,576 neurons in 0.65 seconds. I once tried to do the same on the CPU, and I had to kill it because it was taking so long (it would've taken around 200 seconds, if my terrible arithmetic is accurate). Again, this was also on the Iris Pro, and I know for sure that it'll run a lot faster on my RX 480 once I get it working (~800 GFLOPS vs 5 TFLOPS).

The key to using GPUs is to run lots of parallel, expensive calculations in a single kernel execution, and to keep your data on the GPU for as long as possible.
