### ISSUE TITLE
Current Event callback uses undefined behaviour

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/OpenCL.jl#86]
I learned today [1] that the solution I implemented for user callbacks in [2] is using undefined/illegal behaviour.
I am quite amazed that it worked as long as it did...

````
code_llvm(OpenCL.event_notify, (OpenCL.CL_event, OpenCL.CL_int, Ptr{Void}))
 
%7 = load %jl_value_t*** @jl_pgcstack, align 8
````

I am not quite sure how to solve that problem without reimplementing `Base.SingleAsyncWork` since we can't pass along `evt_id::CL_event, status::CL_int`.

@jakebolewski Any ideas?

[1] https://groups.google.com/forum/#!topic/julia-dev/9J1GYfCyVpE
[2] https://github.com/JuliaGPU/OpenCL.jl/blob/f529546ac3d9aa0517e1d7e4b72856f45284d096/src/event.jl#L97-L106

**Comment by dfdx** [comment]
Can it be the reason for [segfault in tests](https://travis-ci.org/JuliaGPU/OpenCL.jl/jobs/90612668)? (note that I commented out possibly erroneous tests for arrays).

**Comment by vchuravy** [comment]
Yes that is entirely possible and probably my fault. I am going to look
into this. How often do you see it occur?

**Comment by dfdx** [comment]
It is pretty reproducible in Travis (40% of time, in other 60% error is not printed, but build fails, so it may also be caused by segfault). Though, currently I don't have access to a GPU-enabled computer, so cannot test it locally. 

Note 2 things: 

 * `segfault-test` branch is a copy of master with array tests commented out
 * segfault occurs only for Julia v0.4 on Linux, nightly build and Mac are not affected (according to Travis)

**Comment by vchuravy** [comment]
@dfdx Sorry I completely missed the point you were trying to make. I though #87 was already merged and was about to investigate the seqfault you mentionend and wondered why it is still the old code. I think it is time to merge #87 now and that should hopefully solve your issue.

**Comment by dfdx** [comment]
Thanks, that error has gone now. However, I encounter another (minor) issue which might be related to even callbacks - see #92 .
